### ISSUE TITLE
Title is not displayed after folding 

### ISSUE THREAD

**Issue by sarkissm** [melke/markdown-folder#19]
When I toggle folding I see the last line rather than the title itself, e.g. if I have  
# head1

line1
line2
line3

Then after folding I see 

`> line3`

**Comment by paul-howard** [comment]
+1

Everything seems cool in v1.8.0, but I'm seeing the same behavior in v1.9.0-beta0.

**Comment by JoseBlanca** [comment]
Same problem here since 1.9.0

**Comment by JoseBlanca** [comment]
I've asked to the Atom folk about the problem [here](https://discuss.atom.io/t/shown-line-after-folding/32116/4).
The folding behaviour has been changed, so this package is not going to work properly unless is modified. I've tried to do it and I've manage to go a little in the proper direction, but I lack Atom package debugging skills, so I've not been able to fix it.

**Comment by JoseBlanca** [comment]
I really need this package, so I've tried to implent some of its funcionallity.
I don't promise anything. It is my first javascript, my first coffeescript and my first Atom package. But the cycle command is working for me in atom 1.9.8
The code is [here](https://github.com/JoseBlanca/markdown-folding)
I'd really prefer that somebody that know more than me fixes this package, but for the time being my hack could be of some use.

**Comment by monotasker** [comment]
I too am finding the package unusable now, but it is crucial for my workflow. The package author hasn't responded here at all since June. Is the package maintained still or has s/he abandoned it?

**Comment by tshort** [comment]
I'm sorry for the neglect. I wasn't getting Github's notifications. I don't have access to my machine until the middle of the week. If someone finds a fix before I get to it, you can always post a PR.

**Comment by JoseBlanca** [comment]
The problem originated because there was a change in Atom's folding API. Now you can fold a section of a line.
I tried to fix your code, but I didn't know enough, so I tried to do something with the new API just to learn how everything worked. You can find the code in [markdown-folding](https://github.com/JoseBlanca/markdown-folding).
The code is working for me, but it has not been throughly tested and it does not has all the functionality that your package has. It is just working for me.

**Comment by suntong** [comment]
Thanks @JoseBlanca, 

Folding markdown is the reason I install `atom`, but sad to find it broken. Thanks for your work, It  works for me as well, and I'm happy.

**Comment by ghost** [comment]
@JoseBlanca unfortunately your package didn't work for me but appreciate the effort! Would be really really great if owner could debug this small but clutch feature. Thanks!

**Comment by tshort** [comment]
I just pushed a few changes that attempts to fix this. They were not big changes. Let me know if it works.

All of the tests are broken. I think it's unrelated. I didn't write the tests, so it may take a bit to fix those. In the near term, we may have to release a version with broken tests.

**Comment by ghost** [comment]
Awesome, we all very much appreciate your efforts in resolving this. Unfortunately, the issue still persists for me. If you need it, I am happy to help you bug test.

**Comment by tshort** [comment]
Does it act any differently? Did you use git to manually pull in the latest
update?

**Comment by ghost** [comment]
Sorry! It works now THANKS SO MUCH!  Nota bene for others wanting to manually install from Terminal: 

```
git clone https://github.com/tshort/markdown-folder.git
cd markdown-folder
apm install
apm link 
```

**Comment by Nodragem** [comment]
Could we get the changes without using git, just by using the atom install?

**Comment by tshort** [comment]
Of course, but I wanted to take a stab at fixing the tests first.

**Comment by tshort** [comment]
Is this fix still working?

I thought I had it working, but it's acting funny for me. Unfortunately, I'm not able to access my machine where I originally made the change.

**Comment by ghost** [comment]
Yes it still works for me using GitHub Markdown.

**Comment by ghost** [comment]
In case it helps, try adding this to your keymap:

```
# markdown-folder
'atom-text-editor[data-grammar="source gfm"]:not([mini])':
  'alt-t': 'markdown-folder:toggle'
```

**Comment by Nodragem** [comment]
It still does not work for me but I have the version from "atom install". That may be why.

**Comment by mw-coursera** [comment]
works for me in Atom 1.11.1 installing from a fresh clone following https://github.com/tshort/markdown-folder/issues/19#issuecomment-247628036

**Comment by colemanbroad** [comment]
Fixes the header problem for me in Atom 1.12.7, but now cmd-k cmd-0 doesn't unfold properly on any header except the bottom one.

**Comment by lincolnfrias** [comment]
it did not work for me using the regular installation, but worked from a fresh cloning, as suggested by @Orebeer.

**Comment by DouglasUrner** [comment]
I found and installed the package on 1.15.0 using Atom > Preferences > Install (on OS X) and I'm seeing the same "last line instead of heading" behavior. I'll try a clone as per above.

I then tried uninstalling markdown-folder and installing from GitHub using the instructions in #19. That works, but it appears to break the ability to see some of the packages that I have installed. I see a blue "Loading packages" bar for Git Packages and for Deprecated Packages. Checking for Updates results in a red message "Fetching outdated packages and themes failed." The Show output… link displays a message of "undefined." I didn't check updates before doing the Git install so I'm not positive that the markdown-folder install is implicated.

@lincolnfrias do checking for Updates and viewing installed Packages work for you?

**Comment by mediapathic** [comment]
Not working for me, in that I'm getting the last line instead of first line as a fold label. Did the git pull for the latest version thing, but is that still relevant?

ETA: Atom 1.17.2

**Comment by lincolnfrias** [comment]
@DouglasUrner very sorry for the delay, I missed the notification. 

Yes, the checking for updates and viewing installed packages works fine for me. But my setup is different from yours, I am on ubuntu and atom 1.17.
